### ISSUE TITLE
Str object has no attribute 'convert'.

### ISSUE THREAD

**Issue by nyeduHu** [DownrightImpractical/computercraft-stuff#2]
Traceback (most recent call last):
  File "D:\projekts\turtle\py.py", line 4, in <module>
    nfp.img_to_nfp("t.png")
  File "D:\projekts\turtle\nfp.py", line 44, in img_to_nfp
    im = _quantize_with_colors(im, CC_COLORS)
  File "D:\projekts\turtle\nfp.py", line 89, in _quantize_with_colors
    image = image.convert("RGB")
AttributeError: 'str' object has no attribute 'convert'

My python code: 
```
import nfp

nfp.img_to_nfp("t.png")
```

**Comment by nyeduHu** [comment]
What to do?

**Comment by budak7273** [comment]
You are trying to supply `img_to_nfp` with a string. It needs a Pillow Image (see [line 35](https://github.com/DownrightImpractical/computercraft-stuff/blob/master/nfp.py#L35)).

You can find an example of `img_to_nfp` with correct arguments [here](https://github.com/DownrightImpractical/computercraft-stuff/blob/master/convert_nfp.py#L59).
